# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Evolution Pit - Logical Decision. 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Never miss a change in the Heroes of the Storm meta. Read in depth analysis of
  heroes, strategies, maps, and tournament matches.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.evolutionpit.com" # the base hostname & protocol for your site
twitter_username: evopit

# Build settings
markdown: kramdown
paginate: 10
gems: [jekyll-paginate]
